[package]
name = "integ"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
colored = "2"
clap = { version = "2.33", features = ["yaml"] }